/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frommain;


import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UnsupportedLookAndFeelException;
import panelform.pnDSYeuThich;
import panelform.pnDich;


/**
 *
 * @author Admin
 */
public class frmMain extends javax.swing.JFrame {

    static String LOOKANDFEEL = "com.seaglasslookandfeel.SeaGlassLookAndFeel";


    
    
    public frmMain() {
        initComponents();
        chkAwayontop.setSelected(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDich2 = new panelform.pnDich();
        pnQuanly1 = new panelform.pnQuanly();
        pnContainer = new javax.swing.JPanel();
        pnDich = new javax.swing.JPanel();
        pnDich1 = new panelform.pnDich();
        pnThemsuaxoa = new javax.swing.JPanel();
        pnQuanly2 = new panelform.pnQuanly();
        pnYeuthich = new javax.swing.JPanel();
        pnDSYeuThich1 = new panelform.pnDSYeuThich();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuChucnang = new javax.swing.JMenu();
        menuDich = new javax.swing.JMenuItem();
        menuthemsuaxoa = new javax.swing.JMenuItem();
        menuFav = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuThoat = new javax.swing.JMenuItem();
        menuTuyChon = new javax.swing.JMenu();
        chkAwayontop = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuGiaoDien = new javax.swing.JMenu();
        rbtGiaodienMacDinh = new javax.swing.JRadioButtonMenuItem();
        rbtGiaoDienTattoo = new javax.swing.JRadioButtonMenuItem();
        rbtGiaodienwindows = new javax.swing.JRadioButtonMenuItem();
        menuGioithieu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mền Tra Từ Điển");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));

        pnContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnDichLayout = new javax.swing.GroupLayout(pnDich);
        pnDich.setLayout(pnDichLayout);
        pnDichLayout.setHorizontalGroup(
            pnDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDich1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        pnDichLayout.setVerticalGroup(
            pnDichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDich1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pnContainer.add(pnDich, "card2");

        javax.swing.GroupLayout pnThemsuaxoaLayout = new javax.swing.GroupLayout(pnThemsuaxoa);
        pnThemsuaxoa.setLayout(pnThemsuaxoaLayout);
        pnThemsuaxoaLayout.setHorizontalGroup(
            pnThemsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnQuanly2, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        pnThemsuaxoaLayout.setVerticalGroup(
            pnThemsuaxoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnQuanly2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pnContainer.add(pnThemsuaxoa, "card3");

        javax.swing.GroupLayout pnYeuthichLayout = new javax.swing.GroupLayout(pnYeuthich);
        pnYeuthich.setLayout(pnYeuthichLayout);
        pnYeuthichLayout.setHorizontalGroup(
            pnYeuthichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDSYeuThich1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnYeuthichLayout.setVerticalGroup(
            pnYeuthichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDSYeuThich1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnContainer.add(pnYeuthich, "card4");

        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setBorderPainted(false);

        menuChucnang.setText("Chức Năng");

        menuDich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1490705609_circle-edit-search.png"))); // NOI18N
        menuDich.setText("Tra Từ");
        menuDich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDichActionPerformed(evt);
            }
        });
        menuChucnang.add(menuDich);

        menuthemsuaxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1490705590_flat-style-circle-edit.png"))); // NOI18N
        menuthemsuaxoa.setText("Quản Lý Từ");
        menuthemsuaxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuthemsuaxoaActionPerformed(evt);
            }
        });
        menuChucnang.add(menuthemsuaxoa);

        menuFav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1490705581_circle-content-star-favorite.png"))); // NOI18N
        menuFav.setText("Danh Sách Yêu Thích");
        menuFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFavActionPerformed(evt);
            }
        });
        menuChucnang.add(menuFav);
        menuChucnang.add(jSeparator2);

        menuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1490705919_flat-style-circle-turn-on-off.png"))); // NOI18N
        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        menuChucnang.add(menuThoat);

        jMenuBar1.add(menuChucnang);

        menuTuyChon.setText("Tùy Chọn");

        chkAwayontop.setSelected(true);
        chkAwayontop.setText("Luôn ở trên");
        chkAwayontop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAwayontopActionPerformed(evt);
            }
        });
        menuTuyChon.add(chkAwayontop);
        menuTuyChon.add(jSeparator1);

        menuGiaoDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1490705953_circle-content-reduce-decrease.png"))); // NOI18N
        menuGiaoDien.setText("Giao Diện");

        rbtGiaodienMacDinh.setSelected(true);
        rbtGiaodienMacDinh.setText("Mặc Định");
        rbtGiaodienMacDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGiaodienMacDinhActionPerformed(evt);
            }
        });
        menuGiaoDien.add(rbtGiaodienMacDinh);

        rbtGiaoDienTattoo.setText("Tattoo");
        rbtGiaoDienTattoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGiaoDienTattooActionPerformed(evt);
            }
        });
        menuGiaoDien.add(rbtGiaoDienTattoo);

        rbtGiaodienwindows.setText("Windows");
        rbtGiaodienwindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGiaodienwindowsActionPerformed(evt);
            }
        });
        menuGiaoDien.add(rbtGiaodienwindows);

        menuTuyChon.add(menuGiaoDien);

        jMenuBar1.add(menuTuyChon);

        menuGioithieu.setText("Giới Thiệu");

        jMenuItem1.setText("Tác Giả");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuGioithieu.add(jMenuItem1);

        jMenuBar1.add(menuGioithieu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkAwayontopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAwayontopActionPerformed
        if (chkAwayontop.isSelected()) {
            setAlwaysOnTop(true);
        } else {
            setAlwaysOnTop(false);
        }
    }//GEN-LAST:event_chkAwayontopActionPerformed

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuThoatActionPerformed

    private void menuDichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDichActionPerformed
        pnContainer.removeAll();
        pnContainer.repaint();
        pnContainer.revalidate();
        
        pnContainer.add(new pnDich());
        pnContainer.repaint();
        pnContainer.revalidate();
    }//GEN-LAST:event_menuDichActionPerformed

    private void menuthemsuaxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuthemsuaxoaActionPerformed
        pnContainer.removeAll();
        pnContainer.repaint();
        pnContainer.revalidate();

        pnContainer.add(pnThemsuaxoa);
        pnContainer.repaint();
        pnContainer.revalidate();
    }//GEN-LAST:event_menuthemsuaxoaActionPerformed

    private void menuFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFavActionPerformed
        pnContainer.removeAll();
        pnContainer.repaint();
        pnContainer.revalidate();

        pnContainer.add(new pnDSYeuThich());
        pnContainer.repaint();
        pnContainer.revalidate();
    }//GEN-LAST:event_menuFavActionPerformed

    private void rbtGiaodienMacDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGiaodienMacDinhActionPerformed
        rbtGiaodienMacDinh.setSelected(true);
        rbtGiaoDienTattoo.setSelected(false);
        rbtGiaodienwindows.setSelected(false);
        try {
            javax.swing.UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        
    }//GEN-LAST:event_rbtGiaodienMacDinhActionPerformed

    private void rbtGiaoDienTattooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGiaoDienTattooActionPerformed
        
        rbtGiaoDienTattoo.setSelected(true);
        rbtGiaodienMacDinh.setSelected(false);
        rbtGiaodienwindows.setSelected(false);
        try {
            
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");    
           
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
   
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        
    }//GEN-LAST:event_rbtGiaoDienTattooActionPerformed

    private void rbtGiaodienwindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGiaodienwindowsActionPerformed
        rbtGiaodienwindows.setSelected(true);
        rbtGiaoDienTattoo.setSelected(false);
        rbtGiaodienMacDinh.setSelected(false);
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
   
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
    }//GEN-LAST:event_rbtGiaodienwindowsActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       JOptionPane.showMessageDialog(null, "Xây Dựng Bởi: Nguyễn Hoàng Phúc (1400129)\n"
                                            +"Lớp: Kỹ Thuật Phần Mềm - K2 \n"
                                            +"Dưới Sự Hướng Dẫn Của Giáo Viên: Nguyễn Trung Việt", "Giới Thiệu", -1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//                
//            }
            
            javax.swing.UIManager.setLookAndFeel(LOOKANDFEEL);
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem chkAwayontop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuChucnang;
    private javax.swing.JMenuItem menuDich;
    private javax.swing.JMenuItem menuFav;
    private javax.swing.JMenu menuGiaoDien;
    private javax.swing.JMenu menuGioithieu;
    private javax.swing.JMenuItem menuThoat;
    private javax.swing.JMenu menuTuyChon;
    private javax.swing.JMenuItem menuthemsuaxoa;
    private javax.swing.JPanel pnContainer;
    private panelform.pnDSYeuThich pnDSYeuThich1;
    private javax.swing.JPanel pnDich;
    private panelform.pnDich pnDich1;
    private panelform.pnDich pnDich2;
    private panelform.pnQuanly pnQuanly1;
    private panelform.pnQuanly pnQuanly2;
    private javax.swing.JPanel pnThemsuaxoa;
    private javax.swing.JPanel pnYeuthich;
    private javax.swing.JRadioButtonMenuItem rbtGiaoDienTattoo;
    private javax.swing.JRadioButtonMenuItem rbtGiaodienMacDinh;
    private javax.swing.JRadioButtonMenuItem rbtGiaodienwindows;
    // End of variables declaration//GEN-END:variables
}
